# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from platform_management.notification_server import email_pb2 as platform__management_dot_notification__server_dot_email__pb2


class NotificationEmailStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendEmail = channel.unary_unary(
                '/notification_server.NotificationEmail/SendEmail',
                request_serializer=platform__management_dot_notification__server_dot_email__pb2.SendEmailRequest.SerializeToString,
                response_deserializer=platform__management_dot_notification__server_dot_email__pb2.SendEmailResponse.FromString,
                )


class NotificationEmailServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendEmail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NotificationEmailServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendEmail': grpc.unary_unary_rpc_method_handler(
                    servicer.SendEmail,
                    request_deserializer=platform__management_dot_notification__server_dot_email__pb2.SendEmailRequest.FromString,
                    response_serializer=platform__management_dot_notification__server_dot_email__pb2.SendEmailResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'notification_server.NotificationEmail', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class NotificationEmail(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendEmail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/notification_server.NotificationEmail/SendEmail',
            platform__management_dot_notification__server_dot_email__pb2.SendEmailRequest.SerializeToString,
            platform__management_dot_notification__server_dot_email__pb2.SendEmailResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
