# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: platform_management/management_server.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+platform_management/management_server.proto\x12\x11management_server\"$\n\"GetOnlinePaymentCallbackUrlRequest\";\n#GetOnlinePaymentCallbackUrlResponse\x12\x14\n\x0c\x63\x61llback_url\x18\x01 \x01(\t2\x9b\x01\n\nManagement\x12\x8c\x01\n\x1bGetOnlinePaymentCallbackUrl\x12\x35.management_server.GetOnlinePaymentCallbackUrlRequest\x1a\x36.management_server.GetOnlinePaymentCallbackUrlResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'platform_management.management_server_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETONLINEPAYMENTCALLBACKURLREQUEST._serialized_start=66
  _GETONLINEPAYMENTCALLBACKURLREQUEST._serialized_end=102
  _GETONLINEPAYMENTCALLBACKURLRESPONSE._serialized_start=104
  _GETONLINEPAYMENTCALLBACKURLRESPONSE._serialized_end=163
  _MANAGEMENT._serialized_start=166
  _MANAGEMENT._serialized_end=321
# @@protoc_insertion_point(module_scope)
