# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from platform_management import management_server_pb2 as platform__management_dot_management__server__pb2


class ManagementStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetOnlinePaymentCallbackUrl = channel.unary_unary(
                '/management_server.Management/GetOnlinePaymentCallbackUrl',
                request_serializer=platform__management_dot_management__server__pb2.GetOnlinePaymentCallbackUrlRequest.SerializeToString,
                response_deserializer=platform__management_dot_management__server__pb2.GetOnlinePaymentCallbackUrlResponse.FromString,
                )


class ManagementServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetOnlinePaymentCallbackUrl(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ManagementServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetOnlinePaymentCallbackUrl': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOnlinePaymentCallbackUrl,
                    request_deserializer=platform__management_dot_management__server__pb2.GetOnlinePaymentCallbackUrlRequest.FromString,
                    response_serializer=platform__management_dot_management__server__pb2.GetOnlinePaymentCallbackUrlResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'management_server.Management', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Management(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetOnlinePaymentCallbackUrl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/management_server.Management/GetOnlinePaymentCallbackUrl',
            platform__management_dot_management__server__pb2.GetOnlinePaymentCallbackUrlRequest.SerializeToString,
            platform__management_dot_management__server__pb2.GetOnlinePaymentCallbackUrlResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
