# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from ai_services.recom_server import recom_pb2 as ai__services_dot_recom__server_dot_recom__pb2


class RecomaaSStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateModel = channel.unary_unary(
                '/recom_server.RecomaaS/CreateModel',
                request_serializer=ai__services_dot_recom__server_dot_recom__pb2.CreateModelRequest.SerializeToString,
                response_deserializer=ai__services_dot_recom__server_dot_recom__pb2.CreateModelResponse.FromString,
                )
        self.StartColdstart = channel.unary_unary(
                '/recom_server.RecomaaS/StartColdstart',
                request_serializer=ai__services_dot_recom__server_dot_recom__pb2.StartColdstartRequest.SerializeToString,
                response_deserializer=ai__services_dot_recom__server_dot_recom__pb2.StartColdstartResponse.FromString,
                )
        self.StartSimilaritems = channel.unary_unary(
                '/recom_server.RecomaaS/StartSimilaritems',
                request_serializer=ai__services_dot_recom__server_dot_recom__pb2.StartSimilaritemsRequest.SerializeToString,
                response_deserializer=ai__services_dot_recom__server_dot_recom__pb2.StartSimilaritemsResponse.FromString,
                )
        self.StartUserspecific = channel.unary_unary(
                '/recom_server.RecomaaS/StartUserspecific',
                request_serializer=ai__services_dot_recom__server_dot_recom__pb2.StartUserspecificRequest.SerializeToString,
                response_deserializer=ai__services_dot_recom__server_dot_recom__pb2.StartUserspecificResponse.FromString,
                )
        self.Coldstart = channel.unary_unary(
                '/recom_server.RecomaaS/Coldstart',
                request_serializer=ai__services_dot_recom__server_dot_recom__pb2.ColdstartRequest.SerializeToString,
                response_deserializer=ai__services_dot_recom__server_dot_recom__pb2.ColdstartResponse.FromString,
                )
        self.Similaritems = channel.unary_unary(
                '/recom_server.RecomaaS/Similaritems',
                request_serializer=ai__services_dot_recom__server_dot_recom__pb2.SimilaritemsRequest.SerializeToString,
                response_deserializer=ai__services_dot_recom__server_dot_recom__pb2.SimilaritemsResponse.FromString,
                )
        self.Userspecific = channel.unary_unary(
                '/recom_server.RecomaaS/Userspecific',
                request_serializer=ai__services_dot_recom__server_dot_recom__pb2.UserspecificRequest.SerializeToString,
                response_deserializer=ai__services_dot_recom__server_dot_recom__pb2.UserspecificResponse.FromString,
                )


class RecomaaSServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartColdstart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartSimilaritems(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartUserspecific(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Coldstart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Similaritems(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Userspecific(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RecomaaSServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateModel': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateModel,
                    request_deserializer=ai__services_dot_recom__server_dot_recom__pb2.CreateModelRequest.FromString,
                    response_serializer=ai__services_dot_recom__server_dot_recom__pb2.CreateModelResponse.SerializeToString,
            ),
            'StartColdstart': grpc.unary_unary_rpc_method_handler(
                    servicer.StartColdstart,
                    request_deserializer=ai__services_dot_recom__server_dot_recom__pb2.StartColdstartRequest.FromString,
                    response_serializer=ai__services_dot_recom__server_dot_recom__pb2.StartColdstartResponse.SerializeToString,
            ),
            'StartSimilaritems': grpc.unary_unary_rpc_method_handler(
                    servicer.StartSimilaritems,
                    request_deserializer=ai__services_dot_recom__server_dot_recom__pb2.StartSimilaritemsRequest.FromString,
                    response_serializer=ai__services_dot_recom__server_dot_recom__pb2.StartSimilaritemsResponse.SerializeToString,
            ),
            'StartUserspecific': grpc.unary_unary_rpc_method_handler(
                    servicer.StartUserspecific,
                    request_deserializer=ai__services_dot_recom__server_dot_recom__pb2.StartUserspecificRequest.FromString,
                    response_serializer=ai__services_dot_recom__server_dot_recom__pb2.StartUserspecificResponse.SerializeToString,
            ),
            'Coldstart': grpc.unary_unary_rpc_method_handler(
                    servicer.Coldstart,
                    request_deserializer=ai__services_dot_recom__server_dot_recom__pb2.ColdstartRequest.FromString,
                    response_serializer=ai__services_dot_recom__server_dot_recom__pb2.ColdstartResponse.SerializeToString,
            ),
            'Similaritems': grpc.unary_unary_rpc_method_handler(
                    servicer.Similaritems,
                    request_deserializer=ai__services_dot_recom__server_dot_recom__pb2.SimilaritemsRequest.FromString,
                    response_serializer=ai__services_dot_recom__server_dot_recom__pb2.SimilaritemsResponse.SerializeToString,
            ),
            'Userspecific': grpc.unary_unary_rpc_method_handler(
                    servicer.Userspecific,
                    request_deserializer=ai__services_dot_recom__server_dot_recom__pb2.UserspecificRequest.FromString,
                    response_serializer=ai__services_dot_recom__server_dot_recom__pb2.UserspecificResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'recom_server.RecomaaS', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RecomaaS(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/recom_server.RecomaaS/CreateModel',
            ai__services_dot_recom__server_dot_recom__pb2.CreateModelRequest.SerializeToString,
            ai__services_dot_recom__server_dot_recom__pb2.CreateModelResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StartColdstart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/recom_server.RecomaaS/StartColdstart',
            ai__services_dot_recom__server_dot_recom__pb2.StartColdstartRequest.SerializeToString,
            ai__services_dot_recom__server_dot_recom__pb2.StartColdstartResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StartSimilaritems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/recom_server.RecomaaS/StartSimilaritems',
            ai__services_dot_recom__server_dot_recom__pb2.StartSimilaritemsRequest.SerializeToString,
            ai__services_dot_recom__server_dot_recom__pb2.StartSimilaritemsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StartUserspecific(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/recom_server.RecomaaS/StartUserspecific',
            ai__services_dot_recom__server_dot_recom__pb2.StartUserspecificRequest.SerializeToString,
            ai__services_dot_recom__server_dot_recom__pb2.StartUserspecificResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Coldstart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/recom_server.RecomaaS/Coldstart',
            ai__services_dot_recom__server_dot_recom__pb2.ColdstartRequest.SerializeToString,
            ai__services_dot_recom__server_dot_recom__pb2.ColdstartResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Similaritems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/recom_server.RecomaaS/Similaritems',
            ai__services_dot_recom__server_dot_recom__pb2.SimilaritemsRequest.SerializeToString,
            ai__services_dot_recom__server_dot_recom__pb2.SimilaritemsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Userspecific(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/recom_server.RecomaaS/Userspecific',
            ai__services_dot_recom__server_dot_recom__pb2.UserspecificRequest.SerializeToString,
            ai__services_dot_recom__server_dot_recom__pb2.UserspecificResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
