# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: platform_managment/notification_server.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,platform_managment/notification_server.proto\x12\x12platform_managment\"E\n\x10SendEmailRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x0f\n\x07subject\x18\x02 \x01(\t\x12\x11\n\tbody_text\x18\x03 \x01(\t\"\x13\n\x11SendEmailResponse2n\n\x12NotificationServer\x12X\n\tSendEmail\x12$.platform_managment.SendEmailRequest\x1a%.platform_managment.SendEmailResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'platform_managment.notification_server_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SENDEMAILREQUEST._serialized_start=68
  _SENDEMAILREQUEST._serialized_end=137
  _SENDEMAILRESPONSE._serialized_start=139
  _SENDEMAILRESPONSE._serialized_end=158
  _NOTIFICATIONSERVER._serialized_start=160
  _NOTIFICATIONSERVER._serialized_end=270
# @@protoc_insertion_point(module_scope)
